export const ActionTypes ={
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART:"ADD_TO_CART",
    FAVOURITE_PRODUCT:"FAVOURITE_PRODUCT",
    ADD_CATEGORY:"ADD_CATEGORY"



};